### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by JonathanWi** [kwaak/react-native-android-blurryoverlay#2]
Hey @kwaak! 

Just followed all your installation instructions for the package (BTW, maybe you can make it work with the awesome [rnpm](https://github.com/rnpm/rnpm)) but when I launch the app, it instantly crashes.
- Building the project works
- If I remove `<BlurryOverlay />` from the `render()` (not the dependency tho), it works fine (with no Blurry Overlay obviously).

Do you know what could be the cause here?

Thanks a lot in advance

**Comment by kwaak** [comment]
Hmm, an empty component isn't very useful, but it shouldn't crash. I can render an empty component without problems,
Which React-Native version are you using?

**Comment by JonathanWi** [comment]
I'm using RN 0.18.1, thanks for your quick answer!

**Comment by kwaak** [comment]
Just tried in a fresh RN 0.18.

I can make it crash if I forget to add these 2 settings:
- `android/app/build.gradle`

``` gradle
...
android {
    ...
    defaultConfig {
        ...        
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
    }    
    ...
}
...

Are you sure you have those?
```

**Comment by JonathanWi** [comment]
You were right, I forgot these two lines! 

Do I need to be using the Android API 23+ in order for the blur to happen? I'm currently testing on Genymotion, with an emulated Nexus 5 API 19, and no blur happens! Any clue?

Thanks a lot for your help

**Comment by kwaak** [comment]
Unfortunately whatever is currently visible will be "screenshotted" and blurred. If you render the <BlurryOverlay> at the same time as your content, nothing is visible yet.

Try delaying the render of the component untill everything you want blurred is visible. I've updated the example in the readme with a better example.

**Comment by JonathanWi** [comment]
Thanks @kwaak for your replies, it works!
